### ISSUE TITLE
Ocultar datos personales de archivos de Excel

### ISSUE THREAD

**Issue by jdaguilar** [PyBAQ/sar#7]
Saludos.

Estaba revisando el repositorio y encontré que los archivos de Excel manejando datos personales. no encontre otra mejor manera de hacer la observación por medio de un issue.

Les aconsejo que cuando manejen este tipo de datos procuren no dejarlos sin protección, ya que no sabemos a quien le resulte comodo que cualquiera sepa nuestro número personal o correo.

Sin mas que decir muchas gracias y éxito

**Comment by pandrearro** [comment]
Hola @jdaguilar ,

Gracias por la observación, ya la tuvimos en cuenta y es por eso que estamos usando datos de prueba tomados del sistema de Datos Abiertos del gobierno nacional.
